---

- name: set ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "{{ ferm_ipv4_forwarding }}"
    state: present

- name: set ipv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "{{ ferm_ipv6_forwarding }}"
    state: present

- name: set ipv6 forwarding by default
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: "{{ ferm_ipv6_forwarding }}"
    state: present

- name: set ipv6 router advertisement
  sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: "{{ ferm_ipv6_accept_ra }}"
    state: present

- name: set ipv6 router advertisement by default
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "{{ ferm_ipv6_accept_ra }}"
    state: present

- name: set recommended kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ ferm_kernel_params }}"
  ignore_errors: ferm_role_debug
