---

- name: set ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "{{ ferm_ipv4_forwarding }}"
    state: present

- name: set ipv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "{{ ferm_ipv6_forwarding }}"
    state: present

- name: set ipv6 forwarding by default
  sysctl:
    name: net.ipv6.conf.default.forwarding
    value: "{{ ferm_ipv6_forwarding }}"
    state: present

- name: set ipv6 router advertisement
  sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: "{{ ferm_ipv6_accept_ra }}"
    state: present

- name: set ipv6 router advertisement by default
  sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "{{ ferm_ipv6_accept_ra }}"
    state: present

- name: set recommended kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ ferm_kernel_params }}"
  register: ferm_kernel_params_result
  ignore_errors: True

- name: failed to set recommended kernel parameters
  fail: msg="failed to set recommended kernel parameters"
  when: (ferm_kernel_params_result is failed and (ferm_role_debug|bool == false))
