---

- name: ferm restart
  service: name=ferm state=restarted
  when: not ferm_role_debug

- name: ferm restart
  service: name=ferm state=restarted
  when: not ferm_role_debug

- name: ferm daemon-reload
  systemd:
    daemon_reload: yes
  when: not ferm_role_debug
